import type { TrendingClip } from '@/types/trending'

/**
 * Seed clips used as fallback when the trending_clips table is empty.
 * These use placeholder gradient thumbnails since we can't use Twitch CDN URLs
 * without real clip data.
 */
export const SEED_CLIPS: TrendingClip[] = [
  {
    id: 'seed-1',
    external_url: 'https://clips.twitch.tv/example1',
    platform: 'twitch',
    author_name: 'Kai Cenat',
    author_handle: 'kaicenat',
    title: 'KAI REACTS TO THE CRAZIEST FAN ENCOUNTER',
    description: 'IRL · Kai Cenat · Seed data — click "Twitch" to load real clips',
    niche: 'irl',
    view_count: 4_200_000,
    like_count: 312_000,
    velocity_score: 94.2,
    thumbnail_url: null,
    scraped_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    duration_seconds: null,
    velocity: null,
    viral_ratio: null,
    viral_score: null,
    clip_created_at: null,
    streamer_id: null,
    twitch_clip_id: null,
    tier: null,
    early_signal_score: null,
    anomaly_score: null,
    feed_category: null,
  },
  {
    id: 'seed-2',
    external_url: 'https://clips.twitch.tv/example2',
    platform: 'twitch',
    author_name: 'IShowSpeed',
    author_handle: 'ishowspeed',
    title: 'SPEED DOES THE MOST UNEXPECTED THING ON STREAM',
    description: 'IRL · IShowSpeed · Seed data — click "Twitch" to load real clips',
    niche: 'irl',
    view_count: 2_800_000,
    like_count: 198_000,
    velocity_score: 81.7,
    thumbnail_url: null,
    scraped_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    duration_seconds: null,
    velocity: null,
    viral_ratio: null,
    viral_score: null,
    clip_created_at: null,
    streamer_id: null,
    twitch_clip_id: null,
    tier: null,
    early_signal_score: null,
    anomaly_score: null,
    feed_category: null,
  },
  {
    id: 'seed-3',
    external_url: 'https://clips.twitch.tv/example3',
    platform: 'twitch',
    author_name: 'xQc',
    author_handle: 'xqc',
    title: 'XQC LOSES IT OVER THE DUMBEST TAKE EVER',
    description: 'IRL · xQc · Seed data — click "Twitch" to load real clips',
    niche: 'irl',
    view_count: 1_900_000,
    like_count: 145_000,
    velocity_score: 76.3,
    thumbnail_url: null,
    scraped_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    duration_seconds: null,
    velocity: null,
    viral_ratio: null,
    viral_score: null,
    clip_created_at: null,
    streamer_id: null,
    twitch_clip_id: null,
    tier: null,
    early_signal_score: null,
    anomaly_score: null,
    feed_category: null,
  },
  {
    id: 'seed-4',
    external_url: 'https://clips.twitch.tv/example4',
    platform: 'twitch',
    author_name: 'HasanAbi',
    author_handle: 'hasanabi',
    title: 'HASAN HAS THE BEST REACTION TO VIRAL CLIP',
    description: 'IRL · HasanAbi · Seed data — click "Twitch" to load real clips',
    niche: 'irl',
    view_count: 3_500_000,
    like_count: 421_000,
    velocity_score: 88.5,
    thumbnail_url: null,
    scraped_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    duration_seconds: null,
    velocity: null,
    viral_ratio: null,
    viral_score: null,
    clip_created_at: null,
    streamer_id: null,
    twitch_clip_id: null,
    tier: null,
    early_signal_score: null,
    anomaly_score: null,
    feed_category: null,
  },
]
