import type { TrendingClip } from '@/types/trending'

export const SEED_CLIPS: TrendingClip[] = [
  {
    id: 'seed-1',
    external_url: 'https://clips.twitch.tv/example1',
    platform: 'twitch',
    author_name: 'Kai Cenat',
    author_handle: 'kaicenat',
    title: 'KAI REACTS TO THE CRAZIEST FAN ENCOUNTER',
    description: null,
    niche: 'irl',
    view_count: 4_200_000,
    like_count: 312_000,
    velocity_score: 94.2,
    thumbnail_url: null,
    scraped_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'seed-2',
    external_url: 'https://clips.twitch.tv/example2',
    platform: 'twitch',
    author_name: 'IShowSpeed',
    author_handle: 'ishowspeed',
    title: 'SPEED DOES THE MOST UNEXPECTED THING ON STREAM',
    description: null,
    niche: 'irl',
    view_count: 2_800_000,
    like_count: 198_000,
    velocity_score: 81.7,
    thumbnail_url: null,
    scraped_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'seed-3',
    external_url: 'https://clips.twitch.tv/example3',
    platform: 'twitch',
    author_name: 'xQc',
    author_handle: 'xqc',
    title: 'XQC LOSES IT OVER THE DUMBEST TAKE EVER',
    description: null,
    niche: 'irl',
    view_count: 1_900_000,
    like_count: 145_000,
    velocity_score: 76.3,
    thumbnail_url: null,
    scraped_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
  },
  {
    id: 'seed-4',
    external_url: 'https://clips.twitch.tv/example4',
    platform: 'twitch',
    author_name: 'HasanAbi',
    author_handle: 'hasanabi',
    title: 'HASAN HAS THE BEST REACTION TO VIRAL CLIP',
    description: null,
    niche: 'irl',
    view_count: 3_500_000,
    like_count: 421_000,
    velocity_score: 88.5,
    thumbnail_url: null,
    scraped_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
]
